# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/barankrky/dts-yt-downloader/ui/aboutForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_aboutForm(object):
    def setupUi(self, aboutForm):
        aboutForm.setObjectName("aboutForm")
        aboutForm.resize(580, 190)
        self.okbutton = QtWidgets.QPushButton(aboutForm)
        self.okbutton.setGeometry(QtCore.QRect(480, 150, 89, 21))
        self.okbutton.setObjectName("okbutton")
        self.aboutText = QtWidgets.QLabel(aboutForm)
        self.aboutText.setGeometry(QtCore.QRect(20, 40, 551, 101))
        font = QtGui.QFont()
        font.setFamily("Sans")
        self.aboutText.setFont(font)
        self.aboutText.setWordWrap(True)
        self.aboutText.setObjectName("aboutText")
        self.developedLabel = QtWidgets.QLabel(aboutForm)
        self.developedLabel.setGeometry(QtCore.QRect(20, 150, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Sans")
        self.developedLabel.setFont(font)
        self.developedLabel.setObjectName("developedLabel")
        self.appName = QtWidgets.QLabel(aboutForm)
        self.appName.setGeometry(QtCore.QRect(20, 20, 411, 17))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setBold(True)
        font.setWeight(75)
        self.appName.setFont(font)
        self.appName.setObjectName("appName")
        self.appVersion = QtWidgets.QLabel(aboutForm)
        self.appVersion.setGeometry(QtCore.QRect(390, 20, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.appVersion.setFont(font)
        self.appVersion.setObjectName("appVersion")
        self.label = QtWidgets.QLabel(aboutForm)
        self.label.setGeometry(QtCore.QRect(130, 150, 481, 17))
        font = QtGui.QFont()
        font.setFamily("Sans")
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(aboutForm)
        QtCore.QMetaObject.connectSlotsByName(aboutForm)

    def retranslateUi(self, aboutForm):
        _translate = QtCore.QCoreApplication.translate
        aboutForm.setWindowTitle(_translate("aboutForm", "Form"))
        self.okbutton.setText(_translate("aboutForm", "Close"))
        self.aboutText.setText(_translate("aboutForm", "<html><head/><body><p>DTS is a YouTube video download application that stands out with its simple interface and reliability. It was developed to spite other fake applications on the internet. The application is still under development. If there is an error, you can report it to us from the \'Report\' section in the main menu. Thank you for choosing us."))
        self.developedLabel.setText(_translate("aboutForm", "Developed by :"))
        self.appName.setText(_translate("aboutForm", "Download This Shit Youtube Video Downloader"))
        self.appVersion.setText(_translate("aboutForm", "v1.0_beta"))
        self.label.setText(_translate("aboutForm", "<html><head/><body><p><a href=\"https://github.com/barankrky\"><span style=\" text-decoration: underline; color:#0000ff;\">barankrky</span></a>, <a href=\"https://github.com/burakdmrbkr\"><span style=\" text-decoration: underline; color:#0000ff;\">burakdmrbkr</span></a>, thedarklord.</p></body></html>"))
